server:
  port: 8080

spring:
  profiles:
    group:
      local:
        - site-local
        - db-local
      dev:
        - site-dev
        - db-dev
      prod:
    include:
      - db
      - my-service
      - site
    active: prod
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 200
          batch_versioned_data: true
        order_inserts: true # hibernate 내부에 추가한 insert 작업을 먼저 정렬 후 순서대로 insert 작업 실행
        order_updates: true
  web:
    resources:
      add-mappings: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    throw-exception-if-no-handler-found: true


logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace



sms:
  id: ${SMS_ID}
  pw: ${SMS_PW}