server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/playground_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.MariaDBDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 25MB

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
